source 'https://rubygems.org'
gem 'facebook-messenger'
gem 'sinatra'
gem 'httparty'
gem 'puma'
gem 'pry'
gem 'rest-client'
gem 'rspec'
gem 'rake'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
# gem  'sqlite3', '1.3.13'

gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
